### ISSUE TITLE
SSL transport not working with OpenSSL

### ISSUE THREAD

**Issue by itsmehli** [floragunncom/search-guard-ssl#10]
Getting the following error when using openssl. https with openssl works. ssl transport works with JDK (when I set searchguard.ssl.transport.enable_openssl_if_available: false). Any leads on how to resolve appreciated. Thanks.

------
2016-02-27 01:21:14,848][DEBUG][com.floragunn.searchguard.ssl.transport.SearchGuardSSLNettyTransport] [alpha-es02] disconnecting from [{#zen_unicast_3#}{10.140.0.71}{alpha-es03.example.com/10.140.0.71:9300}], AbstractMethodError[null]
[2016-02-27 01:21:16,125][WARN ][com.floragunn.searchguard.ssl.transport.SearchGuardSSLNettyTransport] [alpha-es02] exception caught on transport layer [[id: 0x469c0215, /10.140.0.71:35858 => /10.140.0.132:9300]], closing connection
java.lang.AbstractMethodError
	at org.apache.tomcat.jni.SSL.readFromSSL(Native Method)
	at io.netty.handler.ssl.OpenSslEngine.readPlaintextData(OpenSslEngine.java:364)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:697)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:803)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:846)
	at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1218)
	at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:852)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-02-27 01:21:16,329][DEBUG][com.floragunn.searchguard.ssl.transport.SearchGuardSSLNettyTransport] [alpha-es02] connected to node [{#zen_unicast_3#}{10.140.0.71}{alpha-es03.example.com/10.140.0.71:9300}]

------
OpenSSL info
{
"principal": null,
"peer_certificates": "0",
"ssl_protocol": "TLSv1.2",
"ssl_cipher": "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
"ssl_openssl_available": true,
"ssl_openssl_version": 268443759,
"ssl_openssl_version_string": "OpenSSL 1.0.2f  28 Jan 2016",
"ssl_openssl_non_available_cause": "",
"ssl_provider_http": "OPENSSL",
"ssl_provider_transport_server": "OPENSSL",
"ssl_provider_transport_client": "OPENSSL"
}

------
OS: CentOS Linux release 7.2.1511 (Core)

**Comment by floragunncom** [comment]
maybe related to https://github.com/netty/netty-tcnative/issues/124

Which tcnative version you are using? Pls. downgrade to 1.1.33.Fork11 and check if the error still occurs.

**Comment by floragunncom** [comment]
1.1.33.Fork13 should also work

**Comment by itsmehli** [comment]
Confirm openssl for transport works for 1.1.33.Fork11 and 1.1.33.Fork13 but does not for 1.1.33.Fork14 and 1.1.33.Fork15
