### ISSUE TITLE
ElasticsearchException[DerInputStream.getLength(): lengthTag=109

### ISSUE THREAD

**Issue by runingday** [floragunncom/search-guard-ssl#11]
Getting the following error when start elasticsearch. how to resolve it   
Thanks 

Starting elasticsearch: Exception in thread "main" ElasticsearchException[DerInputStream.getLength(): lengthTag=109, too big.]; nested: IOException[DerInputStream.getLength(): lengthTag=109, too big.];
Likely root cause: java.io.IOException: DerInputStream.getLength(): lengthTag=109, too big.
	at sun.security.util.DerInputStream.getLength(DerInputStream.java:561)
	at sun.security.util.DerValue.init(DerValue.java:365)
	at sun.security.util.DerValue.<init>(DerValue.java:320)
	at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1882)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at com.floragunn.searchguard.ssl.SearchGuardKeyStore.initSSLConfig(SearchGuardKeyStore.java:178)
	at com.floragunn.searchguard.ssl.SearchGuardKeyStore.<init>(SearchGuardKeyStore.java:126)
	at com.floragunn.searchguard.ssl.SearchGuardSSLModule.<init>(SearchGuardSSLModule.java:29)
	at com.floragunn.searchguard.ssl.SearchGuardSSLPlugin.nodeModules(SearchGuardSSLPlugin.java:89)
	at org.elasticsearch.plugins.PluginsService.nodeModules(PluginsService.java:224)
	at org.elasticsearch.node.Node.<init>(Node.java:166)
	at org.elasticsearch.node.Node.<init>(Node.java:128)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.

**Comment by floragunncom** [comment]
Seems that is a problem with your pkcs12 keystore. How you generated this file? Pls. make also sure you set 

<pre>
searchguard.ssl.transport.keystore_type: PKCS12
searchguard.ssl.transport.truststore_type: PKCS12
searchguard.ssl.http.keystore_type: PKCS12
searchguard.ssl.http.truststore_type: PKCS12
</pre>

Default is JKS

**Comment by runingday** [comment]
thanks   i have got it 

but  i have a new problem  when i test ssl 

curl -XGET http://localhost:9200/_searchguard/sslinfo?pretty
{
  "principal" : null,
  "peer_certificates" : "0",
  "ssl_protocol" : null,
  "ssl_cipher" : null,
  "ssl_openssl_available" : false,
  "ssl_openssl_version" : -1,
  "ssl_openssl_version_string" : null,
  "ssl_openssl_non_available_cause" : "java.lang.UnsatisfiedLinkError: /tmp/libnetty-tcnative4581311149030550870.so: libssl.so.1.0.0: cannot open shared object file: No such file or directory",
  "ssl_provider_http" : null,
  "ssl_provider_transport_server" : "JDK",
  "ssl_provider_transport_client" : "JDK"
}

**Comment by runingday** [comment]
From here, I solved the problem   thank you 

java.lang.UnsatisfiedLinkError

Openssl is not installed, see above
Apache Portable Runtime (APR) is not installed, see above
