### ISSUE TITLE
error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small

### ISSUE THREAD

**Issue by PKFresher** [floragunncom/search-guard-ssl#20]
SSL=2.3.1.8.1
SG=2.3.1.0-beta1
ES: 2.3.1
OS:centos 6.4
curl -V  :curl 7.48.0 (x86_64-pc-linux-gnu) libcurl/7.48.0 OpenSSL/1.0.2g zlib/1.2.3

openssl  version   openSSL 1.0.2g  1 Mar 2016

when I test : 
                curl -Ss --insecure -XGET -u kirk:kirk https://192.168.130.88:9200
respone:
                curl: (35) error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small

PIS : 
       [2016-05-11 16:28:05,379][WARN ][com.floragunn.searchguard.ssl.http.netty.SearchGuardSSLNettyHttpServerTransport] [Node088] Caught exception while handli http traffic, closing connection [id: 0xefdb16dd, /192.168.130.88:51228 => /192.168.130.88:9200]
javax.net.ssl.SSLException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1650)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1618)
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1787)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:887)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:761)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1218)
	at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:852)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
I google this
    https://youremindmeofmymother.com/2015/08/21/socat-ssl-ssl-routinesssl3_check_cert_and_algorithmdh-key-too-small/
 
   If I  should  add HDparm into the script

**Comment by PKFresher** [comment]
yeah ,I solve this problem .
java is  openJDK ;
I change it  with java
everything is OK

**Comment by floragunncom** [comment]
to make it clear: you faced this issue with openjdk and with oraclejdk it disappeared. right?
For which exact openjdk version you got his issue?

Btw: we strongly recommend to use Oracle Java 8 (Java 1.7 is really outdated)

**Comment by PKFresher** [comment]
yes.  when  i change  to oraclejdk ,this issue disappeares.
