### ISSUE TITLE
javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?

### ISSUE THREAD

**Issue by iboware** [floragunncom/search-guard-ssl#24]
Hi,
I am getting this error but my kibana works normally with a huge memory leak. I have got OOM a few times in 2 days. I found this in my es logs:  

**System Configuration:**

- Debian 8
- Oracle JDK 8
- OpenSSL 1.0.2h
- netty-tcnative-1.1.33.Fork17-linux-x86_64
- search-guard-ssl/2.3.3.11
- search-guard-2/2.3.3.0-rc1
- ES 2.3.3
- Kibana 4.5

**ES Configuration:**
```
#SearchGuard
searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: /usr/share/elasticsearch/config/web-keystore.jks
searchguard.ssl.http.keystore_password: '********/'
searchguard.ssl.http.truststore_filepath: /usr/share/elasticsearch/config/web-truststore.jks
searchguard.ssl.http.truststore_password: '*******/'
searchguard.ssl.transport.keystore_filepath: /usr/share/elasticsearch/config/elastic1-keystore.jks
searchguard.ssl.transport.keystore_password: '**********/'
searchguard.ssl.transport.truststore_filepath: /usr/share/elasticsearch/config/truststore.jks
searchguard.ssl.transport.truststore_password: '*********/'
searchguard.ssl.transport.enforce_hostname_verification: true
#searchguard.ssl.transport.resolve_hostname: true
searchguard.authcz.admin_dn:
  - "CN=admin,OU=client,O=client,L=Test,C=DE"
searchguard.ssl.transport.enable_openssl_if_available: true
searchguard.ssl.http.enable_openssl_if_available: true
```

**ES Error Log:**
```
[2016-06-17 01:43:16,756][DEBUG][netty.handler.ssl.SslHandler] [id: 0xd4e3dfa9, /my.ip.add.ress:42764 => /10.0.0.4:9200] HANDSHAKEN: TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
[2016-06-17 01:43:16,756][DEBUG][com.floragunn.searchguard.http.XFFResolver] xff resolve /my.ip.add.ress:42764
[2016-06-17 01:43:16,756][DEBUG][com.floragunn.searchguard.http.XFFResolver] no xff done true,false,class org.elasticsearch.http.netty.NettyHttpRequest,{}
[2016-06-17 01:43:16,757][DEBUG][com.floragunn.searchguard.auth.BackendRegistry] Try to extract auth creds from http basic 
[2016-06-17 01:43:16,757][DEBUG][com.floragunn.searchguard.auth.BackendRegistry] User 'kibanaserver' is in cache? true (cache size: 1)
[2016-06-17 01:43:16,763][DEBUG][com.floragunn.searchguard.auth.BackendRegistry] User 'User [name=kibanaserver, roles=[]]' is authenticated
[2016-06-17 01:43:16,763][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] evaluate permissions for User [name=kibanaserver, roles=[]]
[2016-06-17 01:43:16,763][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] requested indices:data/read/search from my.ip.add.ress:42764
[2016-06-17 01:43:16,763][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] Resolve [.kibana] from class org.elasticsearch.action.search.SearchRequest
[2016-06-17 01:43:16,763][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] indicesOptions IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=true, forbid_closed_indices=true]
[2016-06-17 01:43:16,763][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] raw indices [.kibana]
[2016-06-17 01:43:16,763][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] Resolved [.kibana] to {}
[2016-06-17 01:43:16,763][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] requested resolved aliases and indices: [.kibana]
[2016-06-17 01:43:16,763][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] requested resolved types: [config]
[2016-06-17 01:43:16,763][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] mapped roles: [sg_kibana4_server, sg_public]
[2016-06-17 01:43:16,763][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] ---------- evaluate sg_role: sg_kibana4_server
[2016-06-17 01:43:16,763][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]   Try wildcard match for ?kibana
[2016-06-17 01:43:16,763][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]   Wildcard match for ?kibana: [.kibana]
[2016-06-17 01:43:16,763][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]   matches for ?kibana, will check now types [*]
[2016-06-17 01:43:16,763][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]     resolvedActions for ?kibana/*: [indices:*]
[2016-06-17 01:43:16,763][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]     match requested action indices:data/read/search against ?kibana/*: [indices:*]
[2016-06-17 01:43:16,764][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] remaining requested aliases and indices: []
[2016-06-17 01:43:16,764][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] remaining requested resolved types: []
[2016-06-17 01:43:16,764][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] found a match for 'sg_kibana4_server', evaluate other roles for fls/dls purposes
[2016-06-17 01:43:16,764][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] sg_role sg_public is empty
[2016-06-17 01:43:16,771][DEBUG][netty.handler.ssl.SslHandler] Failed to clean up SSLEngine.
javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
	at io.netty.handler.ssl.OpenSslEngine.closeInbound(OpenSslEngine.java:910)
	at org.jboss.netty.handler.ssl.SslHandler.closeEngine(SslHandler.java:591)
	at org.jboss.netty.handler.ssl.SslHandler.channelDisconnected(SslHandler.java:583)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:102)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireChannelDisconnected(Channels.java:396)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:93)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

```

**Comment by floragunncom** [comment]
Where you get a OOM? In Kibana or in elasticsearch?

**Comment by iboware** [comment]
In Kibana. It's memory consumption growing very fast. It has no modifications. I just use official docker image for Kibana. In a few hours it has grown up to 1 GB. I also have one problem with logstash (couchdb_changes plugin) but I am trying to identify it before opening an issue.

**Comment by floragunncom** [comment]
I don't think that this OOM is caused by Search Guard, seems to be a (SSL related) bug in Kibana. Maybe this is somehow related: https://github.com/elastic/kibana/issues/7103 https://github.com/elastic/kibana/issues/6862

**Comment by iboware** [comment]
Yes this seems to be the issue. Thanks. I am closing this.
