### ISSUE TITLE
Not compatible with 5.0.2

### ISSUE THREAD

**Issue by JoeOrtiz** [floragunncom/search-guard-ssl#42]
Appears search-guard-ssl:5.0.1-17 is not compatible with 5.0.2 ?

```
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [search-guard-ssl] is incompatible with Elasticsearch [5.0.2]. Was designed for version [5.0.1]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:108)
	at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:418)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:471)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:209)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:192)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
	at org.elasticsearch.cli.Command.main(Command.java:62)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:42)
```

**Comment by floragunncom** [comment]
no, but 5.0.2 compatible release will come this week.

**Comment by floragunncom** [comment]
release is out, try search-guard-ssl:5.0.2-17
