### ISSUE TITLE
Getting no class found exception

### ISSUE THREAD

**Issue by gundaldo** [floragunncom/search-guard-ssl#52]
Below is the exception I received when starting elasticsearch services (2.4.1):

Exception in thread "main" ElasticsearchException[Could not find plugin class [com.floragunn.searchguard.ssl.SearchGuardSSLPlugin]]; nested: ClassNotFoundException[com.floragunn.searchguard.ssl.SearchGuardSSLPlugin];
Likely root cause: java.lang.ClassNotFoundException: com.floragunn.searchguard.ssl.SearchGuardSSLPlugin
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:463)
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:431)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:129)
        at org.elasticsearch.node.Node.<init>(Node.java:158)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:194)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)

Apart from updating elasticsearch.yml file Do I need to set anything for elasticsearch to recognize SG?

**Comment by gundaldo** [comment]
I can see java files under SG:

/opt/app/elasticsearch/plugins/search-guard-ssl/src/main/java/com/floragunn/searchguard/ssl
$ ls -lrth
total 76K
drwxr-xr-x 2 dba 4.0K Feb 24 15:06 transport
drwxr-xr-x 2 dba 4.0K Feb 24 15:06 util
-rw-r--r-- 1 dba 2.7K Feb 24 15:06 SearchGuardSSLModule.java
drwxr-xr-x 2 dba 4.0K Feb 24 15:06 rest
-rw-r--r-- 1 dba  29K Feb 24 15:06 DefaultSearchGuardKeyStore.java
-rw-r--r-- 1 dba  987 Feb 24 15:06 SearchGuardSSLSettingsFilter.java
-rw-r--r-- 1 dba 5.2K Feb 24 15:06 SearchGuardSSLPlugin.java
-rw-r--r-- 1 dba 1.2K Feb 24 15:06 SearchGuardKeyStore.java
drwxr-xr-x 3 dba 4.0K Feb 24 15:06 http
-rw-r--r-- 1 dba 4.4K Feb 24 15:06 ExternalSearchGuardKeyStore.java

**Comment by floragunncom** [comment]
how did you install the plugin?

**Comment by gundaldo** [comment]
I have downloaded zip file from github and using plugin command installed SG.

plugin install -file:search-guard-ssl

**Comment by floragunncom** [comment]
Please download the zips here

https://oss.sonatype.org/content/repositories/releases/com/floragunn/search-guard-ssl/ https://oss.sonatype.org/content/repositories/releases/com/floragunn/search-guard-2/
or install via

<pre>
bin/plugin install -b com.floragunn/search-guard-2/2.4.1.11
bin/plugin install -b com.floragunn/search-guard-ssl/2.4.1.20
</pre>  

See http://floragunncom.github.io/search-guard-ssl-docs/installation.html and http://floragunncom.github.io/search-guard-docs/installation.html

**Comment by gundaldo** [comment]
Thanks floragunncom, it works now.

But I see below warnings:
[2017-03-02 12:13:42,079][WARN ][com.floragunn.searchguard.ssl.transport.SearchGuardSSLNettyTransport] [qictest] Someone (/192.*.*.*:45183) speaks transport plaintext instead of ssl, will close the channel

How can I avoid these warnings?

**Comment by floragunncom** [comment]
See https://github.com/floragunncom/search-guard-ssl/issues/47
