### ISSUE TITLE
enabled_ciphers and enabled_protocols were simple string instead of list settings

### ISSUE THREAD

**Issue by floragunncom** [floragunncom/search-guard-ssl#61]
<pre>
searchguard.ssl.transport.enabled_ciphers
searchguard.ssl.transport.enabled_protocols
searchguard.ssl.http.enabled_ciphers
searchguard.ssl.http.enabled_protocols
</pre>
must be list settings (arrays) but are as SG SSL 22 and SG 12 simple string setting which leads to the following exception:

<pre>
[2017-06-10T18:15:52,632][ERROR][o.e.b.Bootstrap          ] Exception
java.lang.IllegalArgumentException: unknown setting [searchguard.ssl.http.enabled_protocols.0] did you mean any of [searchguard.ssl.http.enabled_protocols, searchguard.ssl.transport.enabled_protocols, searchguard.ssl.http.enabled_ciphers]?
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:276) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:244) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:138) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.node.Node.<init>(Node.java:328) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.node.Node.<init>(Node.java:232) ~[elasticsearch-5.2.2.jar:5.2.2]
</pre>

**Comment by floragunncom** [comment]
fixed in SG-14 but currently not in SG-SSL itself. This is planned for SG-SSL v23

**Comment by floragunncom** [comment]
fixed with SG-SSL v23
