### ISSUE TITLE
Getting no class found exception

### ISSUE THREAD

**Issue by sbmaggarwal** [floragunncom/search-guard-ssl#64]
```
Caused by: java.lang.ClassNotFoundException: com.floragunn.searchguard.ssl.SearchGuardSSLPlugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)...
```

ES version : 2.4.4

Installed SearchGuard using:
```
bin/plugin install -b com.floragunn/search-guard-ssl/2.4.4.21
bin/plugin install -b com.floragunn/search-guard-2/2.4.4.12
```

Using default keystore. Have following in `elasticsearch.yml` file:
```
searchguard.ssl.transport.keystore_filepath: ./node-0-keystore.jks
searchguard.ssl.transport.keystore_password: changeit
searchguard.ssl.transport.truststore_filepath: ./truststore.jks
searchguard.ssl.transport.truststore_password: changeit
searchguard.authcz.admin_dn:
  - "CN=kirk,OU=client,O=client,L=test, C=DE"
```

Added following maven dependency:
```
<dependency>
    <groupId>com.floragunn</groupId>
    <artifactId>search-guard-ssl</artifactId>
    <version>2.4.4.21</version>
    <scope>provided</scope>
</dependency>
```

My settings:

```
Settings esSettings = Settings.settingsBuilder()
  .put("cluster.name", clusterName)
  .put(SSLConfigConstants.SEARCHGUARD_SSL_TRANSPORT_KEYSTORE_FILEPATH,"path to keystore")
  .put(SSLConfigConstants.SEARCHGUARD_SSL_TRANSPORT_TRUSTSTORE_FILEPATH, "path to keystore")
  .put(SSLConfigConstants.SEARCHGUARD_SSL_TRANSPORT_KEYSTORE_PASSWORD, "changeit")
  .put(SSLConfigConstants.SEARCHGUARD_SSL_TRANSPORT_TRUSTSTORE_PASSWORD, "changeit")
  .build();

TransportClient client = TransportClient
  .builder()
  .settings(esSettings)
  .addPlugin(SearchGuardSSLPlugin.class)
  .build()
  .addTransportAddress(
    new InetSocketTransportAddress(InetAddress.getByName(elasticsearchHost),elasticsearchPort));

  client.prepareGet().putHeader("Authorization", "Basic " + Base64.encodeBase64("admin:admin".getBytes())).get();

        return client;
```

**Comment by floragunncom** [comment]
remove `<scope>provided</scope>`

**Comment by floragunncom** [comment]
@sbmaggarwal ping?

**Comment by sbmaggarwal** [comment]
@floragunncom Thanks, this solved my issue.

**Comment by harika-gudumasu** [comment]
Hi, I am facing the same exception as below
Caused by: java.lang.ClassNotFoundException: com.floragunn.searchguard.ssl.SearchGuardSSLPlugin


where can i add maven dependency? 
Do i need to add it in elasticsearch.yml file?
