### ISSUE TITLE
Netty stacktrace displayed when accessing via HTTP instead of HTTPS

### ISSUE THREAD

**Issue by guy-moller** [floragunncom/search-guard-ssl#65]
* Search Guard and Elasticsearch version
  * SG 5.4.1-12
* JVM version and operating system version
  * Mac, Oracle JDK 1.8
* Number of nodes in your cluster
  * 1, just for testing
* Description of the bug

Up until 5.3.x of ES/SG (I think), SG would output an error message like this when accessing with HTTP instead of HTTPS:

`[2017-06-22T11:08:22,345][WARN ][c.f.s.h.SearchGuardHttpServerTransport] [VrM604N] Someone (/127.0.0.1:57713) speaks http plaintext instead of ssl, will close the channel
`
With 5.4.x, I now get a stacktrace from Netty, and the above warn message is gone.

```
[2017-06-22T11:10:48,733][WARN ][c.f.s.h.SearchGuardHttpServerTransport] [a86F84K] caught exception while handling client http traffic, closing connection [id: 0xb48fb7d2, L:0.0.0.0/0.0.0.0:9200 ! R:/127.0.0.1:57752]
io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 474554202f20485454502f312e310d0a486f73743a ...
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[netty-codec-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.11.Final.jar:4.1.11.Final]
...
```
Is this on purpose?

* Steps to reproduce
  * Fire up a 5.4.x node, enable HTTPS, access with HTTP

**Comment by floragunncom** [comment]
fixed in SG-14 but currently not in SG-SSL itself. This is planned for SG-SSL v23

**Comment by floragunncom** [comment]
fixed with SG-SSL v23
