### ISSUE TITLE
SG SSLException when running sgadmin

### ISSUE THREAD

**Issue by BoyCook** [floragunncom/search-guard-ssl#85]
**Elasticsearch**: 6.2.2
**Searchguard**: 6.2.2
**OS**: Windows Server 2012
**Java**: 1.8.0_151
**Nodes**: 1
**TLS**: Internally generated

I'm trying to initialise searchguard by running the following command:

```
.\sgadmin.bat -cd ..\sgconfig -nhnv -ts ..\..\..\config\trust.jks -tspass "<password>" -ks ..\..\..\config\key.jks -kspass "<password>" -h <domain> -ksalias node -icl
```

My config is a follows (anonymised)

```
searchguard.enterprise_modules_enabled: false

searchguard.ssl.transport.keystore_filepath: key.jks
searchguard.ssl.transport.keystore_password: "<password>"
searchguard.ssl.transport.truststore_filepath: trust.jks
searchguard.ssl.transport.truststore_password: "<password>"

searchguard.ssl.transport.resolve_hostname: false
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.transport.keystore_alias: node

searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: key.jks
searchguard.ssl.http.keystore_password: "<password>"
searchguard.ssl.http.truststore_filepath: trust.jks
searchguard.ssl.http.truststore_password: "<password>"
searchguard.ssl.http.keystore_alias: node

searchguard.authcz.admin_dn:
  -"CN=<domain>,OU=IT,O=<org> LLP,L=London,ST=London,C=GB"
```

I'm getting the following error:

```
Search Guard Admin v6
Will connect to <domain>:9300 ... done
Unable to check whether cluster is sane: None of the configured nodes are available: [{#transport#-1}{I8TkJlT3SlqCOUPe81eyaA}{<domain>}{10.72.8.46:93
00}]
11:41:04.843 [elasticsearch[_client_][transport_client_boss][T#1]] ERROR com.floragunn.searchguard.ssl.transport.SearchGuardSSLNettyTransport - SSL Problem Received
fatal alert: certificate_unknown
javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
        at sun.security.ssl.Alerts.getSSLException(Unknown Source) ~[?:1.8.0_151]
        at sun.security.ssl.SSLEngineImpl.fatal(Unknown Source) ~[?:1.8.0_151]
        at sun.security.ssl.SSLEngineImpl.fatal(Unknown Source) ~[?:1.8.0_151]
        at sun.security.ssl.SSLEngineImpl.recvAlert(Unknown Source) ~[?:1.8.0_151]
        at sun.security.ssl.SSLEngineImpl.readRecord(Unknown Source) ~[?:1.8.0_151]
        at sun.security.ssl.SSLEngineImpl.readNetRecord(Unknown Source) ~[?:1.8.0_151]
        at sun.security.ssl.SSLEngineImpl.unwrap(Unknown Source) ~[?:1.8.0_151]
        at javax.net.ssl.SSLEngine.unwrap(Unknown Source) ~[?:1.8.0_151]
        at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:281) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1215) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1127) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1162) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.16.Final.jar:4.1.16.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.16.Final.jar:4.1.16.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.16.Final.jar:4.1.16.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.16.Final.jar:4.1.16.Final]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
ERR: Cannot connect to Elasticsearch. Please refer to elasticsearch logfile for more information
Trace:
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{I8TkJlT3SlqCOUPe81eyaA}{<domain>}{10.72.8.46:9300}]]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
        at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:60)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:371)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:405)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:394)
        at com.floragunn.searchguard.tools.SearchGuardAdmin.main0(SearchGuardAdmin.java:444)
        at com.floragunn.searchguard.tools.SearchGuardAdmin.main(SearchGuardAdmin.java:123)
```

**Comment by floragunncom** [comment]
That very likely not a but but misconfiguration. It seems that your certificate is not trusted. Pls try https://search-guard.com/tls-certificate-generator/ or https://docs.search-guard.com/latest/offline-tls-tool.html
