### ISSUE TITLE
Absolute paths to certificates/keys not allowed (if config directory is specified?)

### ISSUE THREAD

**Issue by austin987** [floragunncom/search-guard-ssl#88]
* Search Guard and Elasticsearch version:
elasticsearch-6.2.4
search-guard-6.2.4.22.1

* JVM version and operating system version
esalpham1 /etc/elasticsearch/ssl_bind # java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

OS is Gentoo Linux (AMD64)

* Number of nodes in your cluster

Currently 1 (just testing search-guard, eventually for real clusters)

* Description of the bug

We have an internal CA that issues certificates, and are installed in /etc/ssl/. If I tell search-guard to use certs from that location, it bails out with a permission denied error:

```
[2018-06-01T21:30:45,003][INFO ][o.e.n.Node               ] [esalpham1.r15.02a.av1.example.org] initializing ...
[2018-06-01T21:30:45,075][INFO ][o.e.e.NodeEnvironment    ] [esalpham1.r15.02a.av1.example.org] using [1] data paths, mounts [[/ (/dev/vda1)]], net usable_space [8.7gb], net total_space [13.9gb], types [ext4]
[2018-06-01T21:30:45,075][INFO ][o.e.e.NodeEnvironment    ] [esalpham1.r15.02a.av1.example.org] heap size [1007.3mb], compressed ordinary object pointers [true]
[2018-06-01T21:30:45,076][INFO ][o.e.n.Node               ] [esalpham1.r15.02a.av1.example.org] node name [esalpham1.r15.02a.av1.example.org], node ID [YfPoUoTVTjGoXYbxoQK_zw]
[2018-06-01T21:30:45,077][INFO ][o.e.n.Node               ] [esalpham1.r15.02a.av1.example.org] version[6.2.4], pid[12809], build[ccec39f/2018-04-12T20:37:28.497551Z], OS[Linux/4.14.46-vanilla-base-4/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_172/25.172-b11]
[2018-06-01T21:30:45,077][INFO ][o.e.n.Node               ] [esalpham1.r15.02a.av1.example.org] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch.WpK74n2D, -XX:+HeapDumpOnOutOfMemoryError, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -XX:+PrintTenuringDistribution, -XX:+PrintGCApplicationStoppedTime, -Xloggc:logs/gc.log, -XX:+UseGCLogFileRotation, -XX:NumberOfGCLogFiles=32, -XX:GCLogFileSize=64m, -Dcom.sun.management.jmxremote.authenticate=true, -Dcom.sun.management.jmxremote.access.file=/etc/elasticsearch/jmx.access, -Dcom.sun.management.jmxremote.password.file=/etc/elasticsearch/jmx.passwd, -Dcom.sun.management.jmxremote.ssl=false, -Dcom.sun.management.jmxremote.port=54300, -Xloggc:/var/log/elasticsearch/test-alpha3-gc.log, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/etc/elasticsearch]
[2018-06-01T21:30:45,980][INFO ][c.f.s.SearchGuardPlugin  ] ES Config path is /etc/elasticsearch
[2018-06-01T21:30:46,039][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] OpenSSL not available (this is not an error, we simply fallback to built-in JDK SSL) because of java.lang.ClassNotFoundException: io.netty.internal.tcnative.SSL
[2018-06-01T21:30:46,298][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] Config directory is /etc/elasticsearch/, from there the key- and truststore files are resolved relatively
[2018-06-01T21:30:46,300][ERROR][o.e.b.Bootstrap          ] Exception
java.lang.IllegalStateException: failed to load plugin class [com.floragunn.searchguard.SearchGuardPlugin]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:563) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:505) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:422) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:146) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.node.Node.<init>(Node.java:303) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.node.Node.<init>(Node.java:246) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.2.4.jar:6.2.4]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.2.4.jar:6.2.4]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) [elasticsearch-6.2.4.jar:6.2.4]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_172]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:554) ~[elasticsearch-6.2.4.jar:6.2.4]
	... 15 more
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "/etc/ssl/private/host/cert.pem" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_172]
	at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_172]
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_172]
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888) ~[?:1.8.0_172]
	at sun.nio.fs.UnixPath.checkRead(UnixPath.java:795) ~[?:?]
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:49) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144) ~[?:?]
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) ~[?:?]
	at java.nio.file.Files.readAttributes(Files.java:1737) ~[?:1.8.0_172]
	at java.nio.file.Files.isDirectory(Files.java:2192) ~[?:1.8.0_172]
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.checkPath(DefaultSearchGuardKeyStore.java:704) ~[?:?]
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.resolve(DefaultSearchGuardKeyStore.java:193) ~[?:?]
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.initSSLConfig(DefaultSearchGuardKeyStore.java:281) ~[?:?]
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.<init>(DefaultSearchGuardKeyStore.java:145) ~[?:?]
	at com.floragunn.searchguard.ssl.SearchGuardSSLPlugin.<init>(SearchGuardSSLPlugin.java:193) ~[?:?]
	at com.floragunn.searchguard.SearchGuardPlugin.<init>(SearchGuardPlugin.java:183) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_172]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:554) ~[elasticsearch-6.2.4.jar:6.2.4]
	... 15 more
```

Note that the elasticsearch user can read these files just fine:
```
elasticsearch@esalpham1 ~ $ whoami 
elasticsearch
elasticsearch@esalpham1 ~ $ head -n1 /etc/ssl/private/host/cert.pem
-----BEGIN CERTIFICATE-----
elasticsearch@esalpham1 ~ $ head -n1 /etc/ssl/private/host/pkey.pkcs8.nocrypt
-----BEGIN PRIVATE KEY-----
elasticsearch@esalpham1 ~ $ head -n1 /etc/ssl/certs/truststore.pem 
-----BEGIN CERTIFICATE-----
```

I then tried making a symlink to the absolute path:

```
esalpham1 /etc/elasticsearch/ssl_absolute_sym # ls -al
total 8
drwxr-sr-x 2 root elasticsearch 4096 Jun  1 21:34 .
drwxr-s--- 7 root elasticsearch 4096 Jun  1 21:33 ..
lrwxrwxrwx 1 root elasticsearch   33 Jun  1 21:33 cert.pem -> /etc/ssl/private/host/cert.pem
lrwxrwxrwx 1 root elasticsearch   33 Jun  1 21:34 pkey.pkcs8.nocrypt -> /etc/ssl/private/host/pkey.pkcs8.nocrypt
lrwxrwxrwx 1 root elasticsearch   32 Jun  1 21:34 truststore.pem -> /etc/ssl/certs/truststore.pem
```

```
pemcert_filepath: ssl_absolute_sym/cert.pem
pemkey_filepath: ssl_absolute_sym/pkey.pkcs8.nocrypt
pemtrustedcas_filepath: ssl_absolute_sym/truststore.pem
```

Which gives a practically identical error:
```
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "/etc/elasticsearch/ssl_absolute_sym/cert.pem" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_172]
	at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_172]
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_172]
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888) ~[?:1.8.0_172]
	at sun.nio.fs.UnixPath.checkRead(UnixPath.java:795) ~[?:?]
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:49) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144) ~[?:?]
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) ~[?:?]
	at java.nio.file.Files.readAttributes(Files.java:1737) ~[?:1.8.0_172]
	at java.nio.file.Files.isDirectory(Files.java:2192) ~[?:1.8.0_172]
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.checkPath(DefaultSearchGuardKeyStore.java:704) ~[?:?]
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.resolve(DefaultSearchGuardKeyStore.java:193) ~[?:?]
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.initSSLConfig(DefaultSearchGuardKeyStore.java:281) ~[?:?]
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.<init>(DefaultSearchGuardKeyStore.java:145) ~[?:?]
	at com.floragunn.searchguard.ssl.SearchGuardSSLPlugin.<init>(SearchGuardSSLPlugin.java:193) ~[?:?]
	at com.floragunn.searchguard.SearchGuardPlugin.<init>(SearchGuardPlugin.java:183) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_172]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:554) ~[elasticsearch-6.2.4.jar:6.2.4]
```

Next, a relative symlink:

```
esalpham1 /etc/elasticsearch/ssl_relative_sym # ls -al
total 8
drwxr-sr-x 2 root elasticsearch 4096 Jun  1 19:17 .
drwxr-s--- 7 root elasticsearch 4096 Jun  1 21:35 ..
lrwxrwxrwx 1 root elasticsearch   34 Jun  1 18:54 cert.pem -> ../../ssl/private/host/cert.pem
lrwxrwxrwx 1 root elasticsearch   44 Jun  1 18:54 pkey.pkcs8.nocrypt -> ../../ssl/private/host/pkey.pkcs8.nocrypt
lrwxrwxrwx 1 root elasticsearch   33 Jun  1 18:54 truststore.pem -> ../../ssl/certs/truststore.pem
```

```
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "/etc/elasticsearch/ssl_relative_sym/cert.pem" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_172]
	at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_172]
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_172]
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888) ~[?:1.8.0_172]
	at sun.nio.fs.UnixPath.checkRead(UnixPath.java:795) ~[?:?]
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:49) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144) ~[?:?]
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) ~[?:?]
	at java.nio.file.Files.readAttributes(Files.java:1737) ~[?:1.8.0_172]
	at java.nio.file.Files.isDirectory(Files.java:2192) ~[?:1.8.0_172]
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.checkPath(DefaultSearchGuardKeyStore.java:704) ~[?:?]
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.resolve(DefaultSearchGuardKeyStore.java:193) ~[?:?]
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.initSSLConfig(DefaultSearchGuardKeyStore.java:281) ~[?:?]
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.<init>(DefaultSearchGuardKeyStore.java:145) ~[?:?]
	at com.floragunn.searchguard.ssl.SearchGuardSSLPlugin.<init>(SearchGuardSSLPlugin.java:193) ~[?:?]
	at com.floragunn.searchguard.SearchGuardPlugin.<init>(SearchGuardPlugin.java:183) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_172]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:554) ~[elasticsearch-6.2.4.jar:6.2.4]
	... 15 more
```

I also tried relative paths, which failed:
```
pemcert_filepath: ../ssl/private/host/cert.pem
pemkey_filepath: ../ssl/private/host/pkey.pkcs8.nocrypt
pemtrustedcas_filepath: ../ssl/certs/truststore-dev.pem
```

```
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "/etc/elasticsearch/../ssl/private/host/cert.pem" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_172]
	at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_172]
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_172]
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888) ~[?:1.8.0_172]
	at sun.nio.fs.UnixPath.checkRead(UnixPath.java:795) ~[?:?]
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:49) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144) ~[?:?]
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) ~[?:?]
	at java.nio.file.Files.readAttributes(Files.java:1737) ~[?:1.8.0_172]
	at java.nio.file.Files.isDirectory(Files.java:2192) ~[?:1.8.0_172]
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.checkPath(DefaultSearchGuardKeyStore.java:704) ~[?:?]
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.resolve(DefaultSearchGuardKeyStore.java:193) ~[?:?]
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.initSSLConfig(DefaultSearchGuardKeyStore.java:281) ~[?:?]
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.<init>(DefaultSearchGuardKeyStore.java:145) ~[?:?]
	at com.floragunn.searchguard.ssl.SearchGuardSSLPlugin.<init>(SearchGuardSSLPlugin.java:193) ~[?:?]
	at com.floragunn.searchguard.SearchGuardPlugin.<init>(SearchGuardPlugin.java:183) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_172]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:554) ~[elasticsearch-6.2.4.jar:6.2.4]
```

I then tried bindmounting them:
```
esalpham1 /etc/elasticsearch/ssl_bind # mount --bind /etc/ssl/certs/truststore.pem /etc/elasticsearch/ssl_bind/truststore.pem
esalpham1 /etc/elasticsearch/ssl_bind # mount --bind /etc/ssl/private/host/cert.pem cert.pem 
esalpham1 /etc/elasticsearch/ssl_bind # mount --bind /etc/ssl/private/host/pkey.pkcs8.nocrypt pkey.pkcs8.nocrypt 

esalpham1 /etc/elasticsearch/ssl_bind # mount | grep $PWD
/dev/vda1 on /etc/elasticsearch/ssl_bind/truststore.pem type ext4 (rw,relatime,data=ordered)
/dev/vda1 on /etc/elasticsearch/ssl_bind/cert.pem type ext4 (rw,relatime,data=ordered)
/dev/vda1 on /etc/elasticsearch/ssl_bind/pkey.pkcs8.nocrypt type ext4 (rw,relatime,data=ordered)
```

which actually worked! So, afaict, there are two options:
A) copy certs from outside the config dir into the config dir
B) bind mount the certs

The documentation mentions that the certs are relative to the config directory, but doesn't mention that absolute paths are forbidden. It's inconvenient for us to have to configure search-guard in a special way (bindmount/copying certs), instead of using a symlink or pointing to a location under /etc/ssl. I'd like to request:
A) allowing absolute paths to certificates outside of the config directory (for systemwide certs not specific to search-guard)
B) updating the documention to explicitly state that absolute paths outside of the config dir are not allowed.

* Steps to reproduce
Set:
pemcert_filepath: /etc/some/path/not/in/es/config
pemkey_filepath: /etc/some/path/not/in/es/config
pemtrustedcas_filepath: /etc/some/path/not/in/es/config

**Comment by floragunncom** [comment]
Elasticsearch can only read files in its config directory. Thats **not SG related** but its a ES thing because ES is running the JVM with security manager enabled ans does have a policy in effect which denies reading files outside the config dir (which is /etc/elasticsearch/ for rpm/deb installations).

The there is no way to make it work, also symlinks etc will not work.

**Comment by floragunncom** [comment]
@jochenkressin can we update the docs to make clear "to explicitly state that absolute paths outside of the config dir are not allowed."

**Comment by jochenkressin** [comment]
I think it's all in the docs already:

https://docs.search-guard.com/latest/configuring-tls

@austin987 Can you help us here to improve the docs? If the doc says you have to place them relative to the config directory, does that not mean that other locations will not work? What would be a better wording here in your opinion? Thanks!

**Comment by austin987** [comment]
Hi @jochenkressin,

I appreciate that you asked how to improve it rather than just closing invalid :).

I did read the docs, e.g.,:
"Path to the certificates key file (PKCS #8), relative to the config/ directory (mandatory)"

To me, t hat means that the path is relative to the config directory, and this entry is required. It does not necessarily mean that relative paths are mandatory.

I suggest a few changes:
1) "Path to the certificates key file (PKCS #8), which must be under the config/ directory, specified using a relative path (mandatory)"  (for each in the table).
2) Mention on that page that is is because of JVM security manager, not Search Guard.
3) (not as important after [1], but still useful) may be to mention in the same place as [2] that absolute paths/symlinks pointing outside of the config directory won't work. I'll leave it to you to decide if it's worth mentioning that bind mounts DO work ;).

BTW, I'm happy to review / offer suggestions on the doc improvements, if desired (I'm a native English speaker).

**Comment by jochenkressin** [comment]
Thanks very much for your input. For us, this is really vital because since we're working with Search Guard day in and out it's sometimes really hard to spot these kinds of mistakes and glitches in the docs. We will keep the issue open until we have updated the docs accordingly.

**Comment by jochenkressin** [comment]
Update the docs for SG5 and SG6 according to suggestions from @austin987
