### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: com.floragunn.searchguard.ssl.SearchGuardSSLPlugin

### ISSUE THREAD

**Issue by harika-gudumasu** [floragunncom/search-guard-ssl#89]
* Search Guard and Elasticsearch version - 6 &  6.2.2
* JVM version and operating system version -"1.8.0_65" and GEOS Linux Server v6.4.0
* Number of nodes in your cluster - 1
* Description of the bug - java.lang.ClassNotFoundException: com.floragunn.searchguard.ssl.SearchGuardSSLPlugin  while starting elasticsearch after installing search-guard6

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce 
* Logfiles on DEBUG level
-->[2018-06-18T07:38:50,351][WARN ][o.e.b.JNANatives         ] Unable to lock JVM Memory: error=12, reason=Cannot allocate memory
[2018-06-18T07:38:50,353][WARN ][o.e.b.JNANatives         ] This can result in part of the JVM being swapped out.
[2018-06-18T07:38:50,353][WARN ][o.e.b.JNANatives         ] Increase RLIMIT_MEMLOCK, soft limit: 65536, hard limit: unlimited
[2018-06-18T07:38:50,354][WARN ][o.e.b.JNANatives         ] These can be adjusted by modifying /etc/security/limits.conf, for example:
        # allow user 'bwadmind' mlockall
        bwadmind soft memlock unlimited
        bwadmind hard memlock unlimited
[2018-06-18T07:38:50,354][WARN ][o.e.b.JNANatives         ] If you are logged in interactively, you will have to re-login for the new limits to take effect.
[2018-06-18T07:38:50,548][INFO ][o.e.n.Node               ] [lonrs11800] initializing ...
[2018-06-18T07:38:50,615][INFO ][o.e.e.NodeEnvironment    ] [lonrs11800] using [1] data paths, mounts [[/opt (/dev/mapper/rootvg-appvol)]], net usable_space [2.4gb], net total_space [13.7gb], types [ext4]
[2018-06-18T07:38:50,615][INFO ][o.e.e.NodeEnvironment    ] [lonrs11800] heap size [3.9gb], compressed ordinary object pointers [true]
[2018-06-18T07:38:50,851][INFO ][o.e.n.Node               ] [lonrs11800] node name [lonrs11800], node ID [9mL-_atRQh-WJxobezcc_g]
[2018-06-18T07:38:50,852][INFO ][o.e.n.Node               ] [lonrs11800] version[6.2.2], pid[21084], build[10b1edd/2018-02-16T19:01:30.685723Z], OS[Linux/2.6.32-358.18.1.el6.x86_64/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_65/25.65-b01]
[2018-06-18T07:38:50,852][INFO ][o.e.n.Node               ] [lonrs11800] JVM arguments [-Xms4g, -Xmx4g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch.mL9r1o2m, -XX:+HeapDumpOnOutOfMemoryError, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -XX:+PrintTenuringDistribution, -XX:+PrintGCApplicationStoppedTime, -Xloggc:logs/gc.log, -XX:+UseGCLogFileRotation, -XX:NumberOfGCLogFiles=32, -XX:GCLogFileSize=64m, -Des.path.home=/opt/app/tibco/install/elasticsearch-6.2.2, -Des.path.conf=/opt/app/tibco/install/elasticsearch-6.2.2/config]
[2018-06-18T07:38:51,678][INFO ][c.f.s.s.SearchGuardSSLPlugin] ES Config path is /opt/app/tibco/install/elasticsearch-6.2.2/config
[2018-06-18T07:38:51,748][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] Open SSL not available (this is not an error, we simply fallback to built-in JDK SSL) because of java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_x86_64, netty_tcnative_linux_x86_64_fedora, netty_tcnative]
[2018-06-18T07:38:52,142][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] Config directory is /opt/app/tibco/install/elasticsearch-6.2.2/config/, from there the key- and truststore files are resolved relatively
[2018-06-18T07:38:52,232][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] AES-256 not supported, max key length for AES is 128 bit. (That is not an issue, it just limits possible encryption strength. To enable AES 256 install 'Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files')
[2018-06-18T07:38:52,232][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] TLS Transport Client Provider : JDK
[2018-06-18T07:38:52,232][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] TLS Transport Server Provider : JDK
[2018-06-18T07:38:52,232][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] TLS HTTP Provider             : null
[2018-06-18T07:38:52,233][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] Enabled TLS protocols for transport layer : [TLSv1.2, TLSv1.1]
[2018-06-18T07:38:52,233][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] Enabled TLS protocols for HTTP layer      : [TLSv1.2, TLSv1.1]
[2018-06-18T07:38:52,387][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [lonrs11800] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[Could not find plugin class [com.floragunn.searchguard.ssl.SearchGuardSSLPlugin]]; nested: ClassNotFoundException[com.floragunn.searchguard.ssl.SearchGuardSSLPlugin];
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.2.2.jar:6.2.2]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.2.2.jar:6.2.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.2.2.jar:6.2.2]
Caused by: org.elasticsearch.ElasticsearchException: Could not find plugin class [com.floragunn.searchguard.ssl.SearchGuardSSLPlugin]
        at org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:532) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:504) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:422) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:146) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.node.Node.<init>(Node.java:303) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.node.Node.<init>(Node.java:246) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.2.2.jar:6.2.2]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: com.floragunn.searchguard.ssl.SearchGuardSSLPlugin
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_65]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_65]
        at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814) ~[?:1.8.0_65]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_65]
        at org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:530) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:504) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:422) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:146) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.node.Node.<init>(Node.java:303) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.node.Node.<init>(Node.java:246) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.2.2.jar:6.2.2]
        ... 6 more

**Comment by floragunncom** [comment]
How did you install Elasticsearch and the Search Guard plugin? Can you post your installation commands (or scripts/templates/...)?

**Comment by harika-gudumasu** [comment]
I have installed both via offline installation in our linux servers using the below tar files.

elasticsearch-6.2.2.tar
search-guard-6-6.2.2-22.1-sgadmin-standalone.tar

**Comment by floragunncom** [comment]
Can you post your installation commands (or scripts/templates/...)?
sgadmin-standalone.tar looks wrong!

If you want only ssl (without authentication etc) use
https://oss.sonatype.org/content/repositories/releases/com/floragunn/search-guard-ssl/6.2.2-25.2/search-guard-ssl-6.2.2-25.2.zip

If you want ssl + authentication etc. use 
https://oss.sonatype.org/content/repositories/releases/com/floragunn/search-guard-6/6.2.2-22.3/search-guard-6-6.2.2-22.3.zip

See https://docs.search-guard.com/latest/search-guard-installation for more details.
Will close this because it looks not like a bug but wrong installation procedure.
