### ISSUE TITLE
SSL connection failing between logstash and search-guard-ssl

### ISSUE THREAD

**Issue by tomryanx** [floragunncom/search-guard-ssl#9]
I've got elasticsearch using search-guard for transport, no problem.  And I can connect using eg `curl` to elasticsearch (see below).  If I disable SSL in ES/search-guard config, logstash can connect file.  But with SSL for the REST/HTTP API enabled, I get SSL errors on the ES side an transport errors on the logstash side.  I *think* it's something to do with my cert not being trusted.

### Elasticsearch Log (using OpenSSL)
    [2016-02-24 05:17:35,184][WARN ][com.floragunn.searchguard.ssl.http.netty.SearchGuardSSLNettyHttpServerTransport] [localhost] Caught exception while handling client http traffic, closing connection [id: 0xcc859489, /127.0.0.1:39216 => /127.0.0.1:9200]  
    javax.net.ssl.SSLHandshakeException: error:1408A10B:SSL routines:SSL3_GET_CLIENT_HELLO:wrong version number  
        at io.netty.handler.ssl.OpenSslEngine.sslReadErrorResult(OpenSslEngine.java:767)  
        at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:726)  
        at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:803)  
        at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:846)  
        at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1218)  
        at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:852)  
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425)  
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)  
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)  
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)  
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)  
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)  
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)  
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)  
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)  
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)  
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)  
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)  
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)  
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)  
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)  
        at java.lang.Thread.run(Thread.java:745)

### Elasticsearch Log (with `enable_openssl_if_available: false` )
    [2016-02-24 05:30:01,549][WARN ][com.floragunn.searchguard.ssl.http.netty.SearchGuardSSLNettyHttpServerTransport] [localhost] Caught exception while handling client http traffic, closing connection [id: 0x3d430aee, /127.0.0.1:39603 => /127.0.0.1:9200]
    javax.net.ssl.SSLHandshakeException: Client requested protocol TLSv1 not enabled or not supported
        at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1348)
        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:519)
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:799)
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:767)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
        at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1218)
        at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:852)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
    Caused by: javax.net.ssl.SSLHandshakeException: Client requested protocol TLSv1 not enabled or not supported
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1650)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:281)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:269)
        at sun.security.ssl.ServerHandshaker.clientHello(ServerHandshaker.java:486)
        at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:222)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:913)
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:853)
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:851)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1285)
        at org.jboss.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1392)
        at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1255)
        ... 18 more

#############################################################################################
    # HTTP/REST layer SSL                                                                       #
    #                                                                                           #
    #############################################################################################
    # Enable or disable rest layer security - https, (default: false)
    searchguard.ssl.http.enabled: true
    # JKS or PKCS12 (default: JKS)
    searchguard.ssl.http.keystore_type: PKCS12
    # Relative path to the keystore file (this stores the server certificates), must be placed under the config/ dir
    searchguard.ssl.http.keystore_filepath: <snip>
    # Alias name (default: first alias which could be found)
    #searchguard.ssl.http.keystore_alias: my_alias
    # Keystore password (default: changeit)
    searchguard.ssl.http.keystore_password: <snip>
    # Do the clients (typically the browser or the proxy) have to authenticate themself to the http server, default is false
    #searchguard.ssl.http.enforce_clientauth: false
    # JKS or PKCS12 (default: JKS)
    #searchguard.ssl.http.truststore_type: PKCS12
    # Relative path to the truststore file (this stores the client certificates), must be placed under the config/ dir
    #searchguard.ssl.http.truststore_filepath: truststore_https.jks
    # Alias name (default: first alias which could be found)
    #searchguard.ssl.http.truststore_alias: my_alias
    # Truststore password (default: changeit)
    #searchguard.ssl.http.truststore_password: changeit
    # Use native Open SSL instead of JDK SSL if available (default: true)
    #searchguard.ssl.http.enable_openssl_if_available: false

### Output of curl 'https://localhost:9200/_searchguard/sslinfo?pretty'
    {
      "principal" : null,
      "peer_certificates" : "0",
      "ssl_protocol" : "TLSv1.2",
      "ssl_cipher" : "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
      "ssl_openssl_available" : true,
      "ssl_openssl_version" : 268439743,
      "ssl_openssl_version_string" : "OpenSSL 1.0.1k 8 Jan 2015",
      "ssl_openssl_non_available_cause" : "",
      "ssl_provider_http" : "OPENSSL",
      "ssl_provider_transport_server" : "OPENSSL",
      "ssl_provider_transport_client" : "OPENSSL"
    }

### In logstash agent output I see
    Attempted to send a bulk request to Elasticsearch configured at '["https://127.0.0.1:9200/"]', but an error occurred and it failed! Are you sure you can reach elasticsearch from this machine using the configuration provided? {:client_config=>{:hosts=>["https://127.0.0.1:9200/"], :ssl=>{:enabled=>true}, :transport_options=>{:socket_timeout=>0, :request_timeout=>0, :proxy=>nil, :ssl=>{:enabled=>true}}, :transport_class=>Elasticsearch::Transport::Transport::HTTP::Manticore, :logger=>nil, :tracer=>nil, :reload_connections=>false, :retry_on_failure=>false, :reload_on_failure=>false, :randomize_hosts=>false}, :error_message=>"Received fatal alert: handshake_failure", :error_class=>"Manticore::ClientProtocolException", :backtrace=>["/root/logstash-2.1.3/vendor/bundle/jruby/1.9/gems/manticore-0.5.3-java/lib/manticore/response.rb:37:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "/root/logstash-2.1.3/vendor/bundle/jruby/1.9/gems/manticore-0.5.3-java/lib/manticore/response.rb:79:in `call'", "/root/logstash-2.1.3/vendor/bundle/jruby/1.9/gems/manticore-0.5.3-java/lib/manticore/response.rb:256:in `call_once'", "/root/logstash-2.1.3/vendor/bundle/jruby/1.9/gems/manticore-0.5.3-java/lib/manticore/response.rb:153:in `code'", "/root/logstash-2.1.3/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/http/manticore.rb:71:in `perform_request'", "org/jruby/RubyProc.java:281:in `call'", "/root/logstash-2.1.3/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/base.rb:201:in `perform_request'", "/root/logstash-2.1.3/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/http/manticore.rb:54:in `perform_request'", "/root/logstash-2.1.3/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/client.rb:125:in `perform_request'", "/root/logstash-2.1.3/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.15/lib/elasticsearch/api/actions/bulk.rb:87:in `bulk'", "/root/logstash-2.1.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:53:in `non_threadsafe_bulk'", "/root/logstash-2.1.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:38:in `bulk'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/root/logstash-2.1.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:38:in `bulk'", "/root/logstash-2.1.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/common.rb:162:in `safe_bulk'", "/root/logstash-2.1.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/common.rb:101:in `submit'", "/root/logstash-2.1.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/common.rb:86:in `retrying_submit'", "/root/logstash-2.1.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/common.rb:58:in `setup_buffer_and_handler'", "org/jruby/RubyProc.java:281:in `call'", "/root/logstash-2.1.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/buffer.rb:109:in `flush_unsafe'", "/root/logstash-2.1.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/buffer.rb:93:in `interval_flush'", "/root/logstash-2.1.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/buffer.rb:82:in `spawn_interval_flusher'", "/root/logstash-2.1.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/buffer.rb:63:in `synchronize'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/root/logstash-2.1.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/buffer.rb:63:in `synchronize'", "/root/logstash-2.1.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/buffer.rb:82:in `spawn_interval_flusher'", "org/jruby/RubyKernel.java:1479:in `loop'", "/root/logstash-2.1.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/buffer.rb:79:in `spawn_interval_flusher'"], :level=>:error}

### Using openssl s_client

I can see that openssl is having an issue with the server:

    $ openssl s_client -connect 127.0.0.1:9200   | grep Verify 
        Verify return code: 20 (unable to get local issuer certificate)

I then added an intermediary cert from the CA we're using to /usr/share/ca-certificates and updated with update-ca-certificates - but it didn't help.  Not directly.  By specifying the path to the ca-certificates.crt file, it worked just fine:

    # openssl s_client -connect 127.0.0.1:9200 -CAfile /etc/ssl/certs/ca-certificates.crt  | grep Verify 
        Verify return code: 0 (ok)

**Comment by floragunncom** [comment]
It looks like you try to connect via TLSv1 ("Client requested protocol TLSv1 not enabled or not supported" or "routines:SSL3_GET_CLIENT_HELLO:wrong version number") which is disabled in Search Guard SSL for security reasons. Pls. use either TLSv1.1 or TLSv1.2 (don't know yet why logstash is trying to open a TLSv1 session, if you connect via browser like you did above with _searchguard/sslinfo then it seems to work well).

Regarding you openssl s_client it depends on how you generate your certificates and how you PKI looks like. Any more infos on that?

**Comment by tomryanx** [comment]
Thanks for getting back to me so quickly!

I have now 'fixed' if not completely 'solved' my problem: upgrading from openjdk 7 to openjdk 8 makes the problem go away.

After looking at a few things, I was convinced logstash was the 'problem' - using
`openssl s_server -accept 9200 -cert /opt/ssl-private/cert.crt -key /opt/ssl-private/key.key` (names changed to protect the innocent) then copying the SSL session parameters into `openssl sess_id -inform PEM -text` I saw `Protocol  : TLSv1`

When using `openssl s_client -connect localhost:9200` I got `Protocol  : TLSv1.2`

This made me really wonder why logstash would be insisting on TLSv1.  I've been testing with logstash 2.1.3 and 2.2.0, very recent version that should not suffer from this.  Indeed TLSv1.2 appears to have been the default in logstash for some time.

So I googled for "openjdk 7 ssl" and sure enough most of the hits were TLSv1.2 related (in other words, TLSv1.2 wasn't working).  Upgrading the jdk is fine, so I'm considering this issue resolved.

Veilen dank!

**Comment by floragunncom** [comment]
Thx

BTW: We generally recommend to use Oracle Java 8.

**Comment by kubbo** [comment]
how disable SSL in ES/search-guard config?

**Comment by floragunncom** [comment]
@kubbo For Search Guard transport layer SSL is mandatory, http layer ssl is optional

**Comment by floragunncom** [comment]
see also https://floragunn.com/search-guard-ssl-tls/

**Comment by prschmid** [comment]
Ran in to the same issue with setting up the elastic search client. In our case it had to do with the python elasticsearch client no using TLSv1.1 but rather the insecure TLSv1. The details can be found here: http://www.prschmid.com/2016/08/configuring-python-elasticsearch-client.html

**Comment by floragunncom** [comment]
@prschmid great, thanks for the link

**Comment by bounddog** [comment]
I got the solution, I think it should be limitation of the default logstash output elasticsearch plugin.
I used logstash v5.4.2,  I modified the file to workaround:
logstash-5.4.2//vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.2-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb

add bellow code to line 118:
ssl_options[:protocols] = ["TLSv1.2"]

**Comment by himmatb** [comment]
@bounddog  I am using 5.6.9 .. but its not working for me .. 

Please help me !!
