### ISSUE TITLE
Missing zip file for 6.5.3-25.5

### ISSUE THREAD

**Issue by ademariag** [floragunncom/search-guard-ssl#97]
Hi,
the plugin installation failing on elasticsearch 6.5.3 because the zip file is missing from the repository

```
-> Downloading com.floragunn:search-guard-ssl:6.5.3-25.5 from maven central
Exception in thread "main" java.io.FileNotFoundException: https://repo1.maven.org/maven2/com/floragunn/search-guard-ssl/6.5.3-25.5/search-guard-ssl-6.5.3-25.5.zip
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
        at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:380)
        at org.elasticsearch.plugins.InstallPluginCommand.downloadAndValidate(InstallPluginCommand.java:453)
        at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:264)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:229)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:216)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
Caused by: java.io.FileNotFoundException: https://repo1.maven.org/maven2/com/floragunn/search-guard-ssl/6.5.3-25.5/search-guard-ssl-6.5.3-25.5.zip
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3000)
        at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
        at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
        at java.net.URLConnection.getContentLength(URLConnection.java:485)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:407)
        at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:379)
        ... 10 more
```

Regards

**Comment by ademariag** [comment]
https://repo1.maven.org/maven2/com/floragunn/search-guard-ssl/6.5.3-25.5/

**Comment by floragunncom** [comment]
Search Guard SSL will not be released as a separate plugin anymore, due to low usage and high maintenance efforts. The code will eventually be merged into Search Guard beginning with Search Guard 7. See https://docs.search-guard.com/latest/changelog-searchguard-6-x-22_3#search-guard-ssl

But you can use the normal SG plugin and operate it in SSL only mode: https://docs.search-guard.com/latest/search-guard-oem-ssl-only

And, because SSL plugin is open source, you can, of course, build it yourself.
